version: '3'

services:
  mysql_db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: online_shop
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  backend:
    image: backend
    restart: on-failure
    depends_on:
      - mysql_db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/online_shop?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSOWRD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    build:
      context: ./
      dockerfile: Dockerfile
