ALTER TABLE cake
ADD CONSTRAINT PKCAKE PRIMARY KEY (idcake);

ALTER TABLE car
ADD CONSTRAINT PKCAKE PRIMARY KEY (idcar);

ALTER TABLE donut
ADD CONSTRAINT PKCAKE PRIMARY KEY (iddonut);

ALTER TABLE laptop
ADD CONSTRAINT PKCAKE PRIMARY KEY (idlaptop);

ALTER TABLE phone
ADD CONSTRAINT PKCAKE PRIMARY KEY (idphone);